-- MySQL Script generated by MySQL Workbench
-- Pon 30 Jun 2025 20:21:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Action` (
  `idAction` INT(11) NOT NULL AUTO_INCREMENT,
  `goal` DECIMAL(10,2) UNSIGNED NOT NULL,
  `collected` DECIMAL(10,2) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(10000) NOT NULL,
  `visible` TINYINT NULL,
  PRIMARY KEY (`idAction`),
  UNIQUE INDEX `idAction_UNIQUE` (`idAction` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `displayname` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Donation` (
  `amount` DECIMAL(10,2) NOT NULL,
  `idAction` INT(11) NOT NULL,
  `idUser` INT(11) NOT NULL,
  `donationTime` DATETIME NOT NULL,
  PRIMARY KEY (`idAction`, `idUser`),
  INDEX `fk_ActionDonation_User1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_ActionDonation_Action1`
    FOREIGN KEY (`idAction`)
    REFERENCES `mydb`.`Action` (`idAction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActionDonation_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`ActionOwner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ActionOwner` (
  `idUser` INT(11) NOT NULL,
  `idAction` INT(11) NOT NULL,
  `isCollab` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUser`, `idAction`),
  INDEX `fk_ActionOwner_Action1_idx` (`idAction` ASC) VISIBLE,
  CONSTRAINT `fk_ActionOwner_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActionOwner_Action1`
    FOREIGN KEY (`idAction`)
    REFERENCES `mydb`.`Action` (`idAction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comment` (
  `idComment` INT(11) NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `idUser` INT(11) NOT NULL,
  `idAction` INT(11) NOT NULL,
  PRIMARY KEY (`idComment`),
  UNIQUE INDEX `idComment_UNIQUE` (`idComment` ASC) VISIBLE,
  INDEX `fk_Comment_User1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_Comment_Action1_idx` (`idAction` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Action1`
    FOREIGN KEY (`idAction`)
    REFERENCES `mydb`.`Action` (`idAction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `username` VARCHAR(40) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `owner` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Report` (
  `idReport` INT NOT NULL AUTO_INCREMENT,
  `reportType` SMALLINT NOT NULL,
  `text` VARCHAR(500) NOT NULL,
  `created` DATETIME NOT NULL,
  `idUserReported` INT(11) NULL,
  `idActionReported` INT(11) NULL,
  `idCommentReported` INT(11) NULL,
  `idUserCreated` INT(11) NOT NULL,
  `handledBy` VARCHAR(40) NULL,
  PRIMARY KEY (`idReport`),
  INDEX `fk_Report_User1_idx` (`idUserReported` ASC) VISIBLE,
  INDEX `fk_Report_Action1_idx` (`idActionReported` ASC) VISIBLE,
  INDEX `fk_Report_Comment1_idx` (`idCommentReported` ASC) VISIBLE,
  INDEX `fk_Report_User2_idx` (`idUserCreated` ASC) VISIBLE,
  INDEX `fk_Report_Admin1_idx` (`handledBy` ASC) VISIBLE,
  CONSTRAINT `fk_Report_User1`
    FOREIGN KEY (`idUserReported`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_Action1`
    FOREIGN KEY (`idActionReported`)
    REFERENCES `mydb`.`Action` (`idAction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_Comment1`
    FOREIGN KEY (`idCommentReported`)
    REFERENCES `mydb`.`Comment` (`idComment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_User2`
    FOREIGN KEY (`idUserCreated`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_Admin1`
    FOREIGN KEY (`handledBy`)
    REFERENCES `mydb`.`Admin` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Refund`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Refund` (
  `idRefund` INT NOT NULL AUTO_INCREMENT,
  `reason` VARCHAR(200) NOT NULL,
  `idAction` INT(11) NOT NULL,
  `idUser` INT(11) NOT NULL,
  PRIMARY KEY (`idRefund`),
  INDEX `fk_Refund_ActionDonation1_idx` (`idAction` ASC, `idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Refund_ActionDonation1`
    FOREIGN KEY (`idAction` , `idUser`)
    REFERENCES `mydb`.`Donation` (`idAction` , `idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notification` (
  `idNotification` INT NOT NULL AUTO_INCREMENT,
  `idUserReceiver` INT(11) NOT NULL,
  `text` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idNotification`),
  INDEX `fk_Notification_User1_idx` (`idUserReceiver` ASC) VISIBLE,
  CONSTRAINT `fk_Notification_User1`
    FOREIGN KEY (`idUserReceiver`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DonationReport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DonationReport` (
  `idDonationReport` INT NOT NULL AUTO_INCREMENT,
  `User_idUser` INT(11) NOT NULL,
  PRIMARY KEY (`idDonationReport`),
  INDEX `fk_DonationReport_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_DonationReport_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Review` (
  `stars` SMALLINT NOT NULL,
  `text` VARCHAR(200) NOT NULL,
  `idUser` INT(11) NOT NULL,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `fk_Review_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
